services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: taskflow_api
    env_file:
      - ../api/.env
    ports:
      - "8000:8000"
    networks:
      - task_network
    volumes:
      - ../api:/app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: taskflow_db
    restart: always
    env_file:
      - ../api/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  task_network:
    driver: bridge

volumes:
  pg_data:
